package projeto_compilador;

public enum TypeToken {
	ENDFILE(0, "END OF FILE"), CARACTER(1, "LETRA"), DIGITO(2, "NUMERAL"), DESCONHECIDO(3, "INVALIDO"),
	INTEIRO(4, "NUMERO INTEIRO"), DECIMAL(5, "NUMERO PONTO FLUTUANTE"), IDENTIFICADOR(6, "IDENTIFICADOR"),
	MULTIPLICAO(7, "OPERADOR MULT (*)"), DIVISAO(8, "OPERADOR DIV (/)"), SOMA(9, "OPERADOR SOMA (+)"),
	SUBTRACAO(10, "OPERADOR SUB (-)"), ABRE_PARENTESES(11, "ABERTURA DE PARENTESES |(|"),
	FECHA_PARENTESES(12, "FECHAMENTO DE PARENTESES |)|"), ATRIBUICAO(13, "ATRIBUICAO (=)"),
	IGUALDADE(14, "COMPARACAO (==)"), DIFERENCA(14, "DIFERENCA (!=)"), COMENTARIO(17, "COMENTARIO"),
	RESERVADO(18, "PALAVRA RESERVADA"), MENOR_QUE(19, "MENOR QUE (<)"), MENOR_IGUAL(20, "MENOR IGUAL (<=)"),
	MAIOR_QUE(21, "MAIOR QUE (>)"), MAIOR_IGUAL(22, "MAIOR IGUAL (>=)"), ABRE_BLOCO(23, "ABERTURA DE BLOCK ({)"),
	FECHA_BLOCO(24, "FECHAMENTO DE BLOCO (})"), VIRGULA(25, "VIRGULA (,)"), PONTO_VIRGULA(26, "PONTO VIRGULA (;)"),
	PR_INT(27, "PALAVRA RESERVADA INT"), PR_FLOAT(28, "PALAVRA RESERVADA FLOAT"), PR_CHAR(29, "PALAVRA RESERVADA CHAR"),
	PR_FOR(30, "PALAVRA RESERVADA FOR"), PR_DO(31, "PALAVRA RESERVADA DO"), PR_WHILE(32, "PALAVRA RESERVADA WHILE"),
	PR_ELSE(33, "PALAVRA RESERVADA ELSE"), PR_IF(34, "PALAVRA RESERVADA IF"), PR_MAIN(35, "PALAVRA RESERVADA MAIN"),
	ABRE_COLCHETE(36, "ABERTURA DE COLCHETE ([)"), FECHA_COLCHETE(37, "FECHAMENTO DE COLCHETE (])");

	private final String nome;
	private final int classe;

	TypeToken(int classe, String nome) {
		this.classe = classe;
		this.nome = nome;
	}

	public int getClasse() {
		return this.classe;
	}

	public String getNome() {
		return this.nome;
	}

}